config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :home
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  namespace :admin do
    resources :dashboard
    resources :posts
    resources :users
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  properties :json
#  cover      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#  content    :text(65535)
#  visible    :boolean          default(TRUE)
#

class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :cover, CoverUploader
  extend FriendlyId
  friendly_id :title, use: :slugged

  VISIBILITY = [['Ya', true], ['Tidak', false]]
  scope :visible, -> { where(visible: true) }

  validates_presence_of :title, :content, :cover, :user_id
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  # GET /admin/posts.json
  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /admin/posts/1
  # GET /admin/posts/1.json
  def show
  end

  # GET /admin/posts/new
  def new
    @post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  # POST /admin/posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/posts/1
  # PATCH/PUT /admin/posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/posts/1
  # DELETE /admin/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :cover, :content, :user_id, :properties, :visible)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 9)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:properties, :cover, :user_id)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_form.html.slim
- if @post.errors.any?
  .alert.alert-danger
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = pluralize(@post.errors.count, 'error')
    |  encountered:
    ul
      - @post.errors.full_messages.each do |message|
        li
          = message
= simple_form_for @post, as: :post, url: (@post.new_record? ? admin_posts_path : admin_post_path(@post)), html: { class: 'form-horizontal', method: (@post.new_record? ? 'post' : 'put')} do |f|
  .panel-body
    .row
      .col-lg-12
        .col-md-6
          = f.input :title, label: 'Judul', input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-6
          = f.input :cover, as: :file, input_html: { class: 'form-control' }
      - unless @post.new_record? and @post.cover.blank?
        .col-lg-12
          .col-md-6
            = image_tag(@post.cover.preview.url)
      .col-lg-12
        .col-md-6
          = f.input :content, as: :text, label: 'Konten', input_html: { class: 'form-control summernote' }
      .col-lg-12
        .col-md-6
          = f.input :user_id, as: :select, label: 'Penulis', collection: User.user_only.map{|usr| [usr.name, usr.id]}, input_html: { class: 'form-control select2' }
      .col-lg-12
        .col-md-2
          = f.input :visible, label: 'Tampilkan', as: :select, collection: Post::VISIBILITY , input_html: { class: 'form-control' }

  .panel-footer
    = link_to admin_posts_path, class: 'btn btn-default' do
      i.fa.fa-undo Back
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/posts/edit.html.slim
section.content-header
  h1
    |  Post
    small
      | Edit
  ol.breadcrumb
    li
      = link_to admin_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | Edit Post
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'

app/views/admin/posts/index.html.slim
.row
  .col-md-12
    .box
      .box-header.with-border
        h3.box-title List Post
        .pull-right
          = link_to 'Add Post', new_admin_post_path, class: 'btn btn-success btn-md'
      /! /.box-header
      .box-body
        table.table.table-bordered
          tbody
            tr
              th style=("width: 10px") #
              th Judul
              th Konten
              th Status
              th Action
            - unless @posts.blank?
              - @posts.each do |post|
                tr
                  td= post.id
                  td= post.title
                  td= raw(post.content)
                  td= post.visible? ? 'Tampil' : 'Sembunyi'
                  td
                    = link_to edit_admin_post_path(post) do
                      i.fa.fa-pencil
                    = link_to admin_post_path(post), data: {method: 'DELETE', confirm: 'Are you sure want to delete this post?'} do
                      i.fa.fa-trash-o
      /! /.box-body
      .box-footer.clearfix
        = will_paginate @posts, renderer: BootstrapPagination::Rails

app/views/admin/posts/new.html.slim
section.content-header
  h1
    |  Post
    small
      | New
  ol.breadcrumb
    li
      = link_to admin_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | New Post
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'