config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :home
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  namespace :admin do
    resources :dashboard
    resources :posts
    resources :users
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/admin/_header.html.slim
header.main-header
  = link_to root_path, class: 'logo', target: '_blank' do
    span.logo-lg
      b
        | Home
  nav.navbar.navbar-static-top[role="navigation"]
    a.sidebar-toggle[href="#" data-toggle="offcanvas" role="button"]
      span.sr-only
        | Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.user.user-menu
          a.dropdown-toggle[href="#" data-toggle="dropdown"]
            = image_tag('user.png', class: 'user-image', alt: "User Image")
            span.hidden-xs
              = current_user.email
          ul.dropdown-menu
            li.user-header
              = image_tag('user.png', class: 'img-circle', alt: "User Image")
              p
                Admin
            li.user-body
              .row
                .col-xs-4.text-center

                .col-xs-4.text-center

                .col-xs-4.text-center

            li.user-footer
              .pull-right
                = link_to "Sign Out", destroy_user_session_path, data: {method: 'DELETE'}, class: 'btn btn-default btn-flat'

app/views/shared/admin/_menu_sidebar.html.slim
li.header MAIN NAVIGATION
li class="#{is_active_path?('dashboard') ? 'active' : ''}"
  = link_to admin_dashboard_index_path do
    i.fa.fa-dashboard
    span Dashboard
li class="#{is_active_path?('users') ? 'active' : ''}"
  = link_to admin_users_path do
    i.fa.fa-user
    span Users
li class="#{is_active_path?('posts') ? 'active' : ''}"
  = link_to admin_posts_path do
    i.fa.fa-book
    span Posts

app/views/shared/admin/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'QuizMaster.', root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - unless user_signed_in?
        = form_for(:user, :url => session_path(:user)) do |f|
          ul.nav.navbar-nav[style="float: right"]
            li.login-field
              = f.email_field :email, class: 'form-control', placeholder: User.human_attribute_name(:email), autofocus: true
            li.login-field
              = f.password_field :password, class: 'form-control', placeholder: User.human_attribute_name(:password), autocomplete: 'off', value: nil
              = link_to "Forgot your password?", new_password_path(:user)
            li.login-field
              = f.submit 'Sign In', class: 'btn btn-info btn-block'

app/views/shared/admin/_sidebar.html.slim
aside.main-sidebar
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! Sidebar user panel
    .user-panel
      .pull-left.image
        = image_tag('user.png', alt: 'User Image', class: 'img-circle')
      .pull-left.info
        p= current_user.email
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    /! search form
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    /! /.search form
    /! sidebar menu: : style can be found in sidebar.less
    ul.sidebar-menu
      = render 'shared/admin/menu_sidebar'